project:
  type: website

website:
  title: "Peter Bull"
  navbar:
    right:
      - icon: house
        href: index.html
      - icon: github
        href: https://github.com/peterbull
      - about.ipynb
      
format:
  html:
    theme: cosmo
    css: styles.css

execute:
  freeze: auto
