project:
  type: website

website:
  title: "peterbull.github.io"
  navbar:
    right:
      - about.ipynb
      - icon: github
        href: https://github.com/peterbull
format:
  html:
    theme: cosmo
    css: styles.css



